from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class DevicePort(Protocol):
    def doctor(self) -> dict[str, Any]: ...
    def install_apk(self, apk: Path) -> None: ...
    def start_supervisor(self) -> None: ...
    def launch_app(self) -> None: ...
    def stop_service(self) -> None: ...
    def kill_qemu(self) -> None: ...
    def count_qemu_processes(self) -> int: ...
    def collect_facts(self) -> dict[str, Any]: ...
    def reboot(self, timeout_seconds: float) -> None: ...
    def logcat(self) -> str: ...


class ControllerPort(Protocol):
    def status(self) -> dict[str, Any]: ...
    def capabilities(self) -> list[dict[str, Any]]: ...
    def profiles(self) -> list[dict[str, Any]]: ...
    def images(self) -> list[dict[str, Any]]: ...
    def vms(self) -> list[dict[str, Any]]: ...
    def apply_vm(self, vm_id: str, request: dict[str, Any], timeout_seconds: float) -> dict[str, Any]: ...
    def import_image(self, request_path: Path, timeout_seconds: float) -> dict[str, Any]: ...
    def upload_image(
        self, artifact_id: str, path: Path, sha256: str, timeout_seconds: float
    ) -> dict[str, Any]: ...
    def guest_ssh(self, target: str, command: str, timeout_seconds: float) -> None: ...
    def recovery_ssh(self, vm_id: str, user: str, command: str, timeout_seconds: float) -> None: ...
    def set_controller_reachable(self, reachable: bool) -> bool: ...


class MeshLabPort(Protocol):
    def wait_for_node(self, name: str, timeout_seconds: float) -> dict[str, Any] | str: ...
